name: Validate with hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "10 17 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: home-assistant/actions/hassfest@master
